name: Auto Commit Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Rulează automat la fiecare oră

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Folosim token-ul personalizat, nu cel implicit

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT3 }}@github.com/danimoncerro/saas-platform.git

      - name: Check for changes
        id: git_status
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git commit -m "Auto-update de la ChatGPT"
          git push origin main



