name: Auto Commit Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"  # Rulează automat la fiecare 3 minute

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push changes
        env:
          GH_PAT3: ${{ secrets.GH_PAT3 }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT3}@github.com/danimoncerro/saas-platform.git
          git add .
          git commit -m "Auto-update de la ChatGPT" || echo "No changes to commit"
          git push origin main




