- name: Push changes
  env:
    GH_PAT: ${{ secrets.GH_PAT1 }}
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git remote set-url origin https://x-access-token:${GH_PAT1}@github.com/danimoncerro/saas-platform.git
    git add .
    git commit -m "Auto-update de la ChatGPT"
    git push origin main

