name: Auto Commit Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/3 * * * *"  # Rulează automat la fiecare 3 minute
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Add empty commit to force update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Forcing auto-commit execution"
          git push

      
      - name: Push changes
        env:
          GH_PAT3: ${{ secrets.GH_PAT3 }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update de la GitHub Actions" --allow-empty || echo "No changes to commit"
          git push origin main


jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add empty commit to force update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Forcing auto-commit execution"
          git push




